"""add_refresh_token_columns_to_users

Revision ID: 31212482295b
Revises: 969b5cedf9d1
Create Date: 2026-01-06 22:07:03.537551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31212482295b'
down_revision: Union[str, Sequence[str], None] = '969b5cedf9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True), schema='identity')
    op.add_column('users', sa.Column('refresh_token_expiry_time', sa.DateTime(timezone=True), nullable=True), schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expiry_time', schema='identity')
    op.drop_column('users', 'refresh_token', schema='identity')
    # ### end Alembic commands ###
