"""added_identity_tables

Revision ID: 8810c07a5b6a
Revises: 
Create Date: 2026-01-03 18:43:45.465935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8810c07a5b6a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_roles_id'), 'roles', ['id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_roles_normalized_name'), 'roles', ['normalized_name'], unique=True, schema='identity')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_id'), 'users', ['id'], unique=False, schema='identity')
    op.create_table('role_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('claim_name', sa.String(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.UUID(), nullable=True),
    sa.Column('last_modified_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_role_claims_id'), 'role_claims', ['id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_role_claims_role_id'), 'role_claims', ['role_id'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_role_claims_role_id'), table_name='role_claims', schema='identity')
    op.drop_index(op.f('ix_identity_role_claims_id'), table_name='role_claims', schema='identity')
    op.drop_table('role_claims', schema='identity')
    op.drop_index(op.f('ix_identity_users_id'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_index(op.f('ix_identity_roles_normalized_name'), table_name='roles', schema='identity')
    op.drop_index(op.f('ix_identity_roles_id'), table_name='roles', schema='identity')
    op.drop_table('roles', schema='identity')
    # ### end Alembic commands ###
