"""added_account_settings_columns_in_user_Table

Revision ID: d78cd28231e6
Revises: 1a5fd0dba611
Create Date: 2026-02-02 21:58:12.064762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types.guid_type import GUID

# revision identifiers, used by Alembic.
revision: str = 'd78cd28231e6'
down_revision: Union[str, Sequence[str], None] = '1a5fd0dba611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=1024), nullable=True), schema='identity')
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True), schema='identity')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('false')), schema='identity')
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default=sa.text('false')), schema='identity')
    op.add_column('users', sa.Column('email_verification_code', GUID(), nullable=True), schema='identity')
    op.add_column('users', sa.Column('email_verification_code_expiry_time', sa.DateTime(timezone=True), nullable=True), schema='identity')
    op.add_column('users', sa.Column('forgot_password_verification_code', GUID(), nullable=True), schema='identity')
    op.add_column('users', sa.Column('forgot_password_verification_code_expiry_time', sa.DateTime(timezone=True), nullable=True), schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'forgot_password_verification_code_expiry_time', schema='identity')
    op.drop_column('users', 'forgot_password_verification_code', schema='identity')
    op.drop_column('users', 'email_verification_code_expiry_time', schema='identity')
    op.drop_column('users', 'email_verification_code', schema='identity')
    op.drop_column('users', 'email_confirmed', schema='identity')
    op.drop_column('users', 'is_active', schema='identity')
    op.drop_column('users', 'phone_number', schema='identity')
    op.drop_column('users', 'profile_image_url', schema='identity')
    # ### end Alembic commands ###
