"""Create users Table

Revision ID: df4f63ef2f0c
Revises: 
Create Date: 2025-07-28 09:58:07.230604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4f63ef2f0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create schema if it doesn't exist
    op.execute("CREATE SCHEMA IF NOT EXISTS \"Identity\"")
    
    op.create_table('Users',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('FullName', sa.String(), nullable=False),
    sa.Column('Hashed_Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    schema='Identity'
    )
    op.create_index(op.f('ix_Identity_Users_Id'), 'Users', ['Id'], unique=False, schema='Identity')
    op.create_index(op.f('ix_Identity_Users_Email'), 'Users', ['Email'], unique=True, schema='Identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Identity_Users_email'), table_name='Users', schema='Identity')
    op.drop_index(op.f('ix_Identity_Users_Id'), table_name='Users', schema='Identity')
    op.drop_table('Users', schema='Identity')
    # ### end Alembic commands ###
