"""identity_and_logger_tables

Revision ID: e01fcd6d635d
Revises: 
Create Date: 2026-02-12 20:28:57.145914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.types.email_status_type import EmailStatusType
from app.models.types.guid_type import GUID

# revision identifiers, used by Alembic.
revision: str = 'e01fcd6d635d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('normalized_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', GUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_roles_is_system'), 'roles', ['is_system'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_roles_normalized_name'), 'roles', ['normalized_name'], unique=True, schema='identity')
    op.create_table('users',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1024), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('email_verification_code', GUID(), nullable=True),
    sa.Column('email_verification_code_expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forgot_password_verification_code', GUID(), nullable=True),
    sa.Column('forgot_password_verification_code_expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', GUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_phone_number'), 'users', ['phone_number'], unique=False, schema='identity')
    op.create_table('email_logs',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('from_email', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('to', sa.Text(), nullable=True),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('bcc', sa.Text(), nullable=True),
    sa.Column('total_email_sent', sa.Integer(), nullable=False),
    sa.Column('status', EmailStatusType(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', GUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='logger'
    )
    op.create_index(op.f('ix_logger_email_logs_status'), 'email_logs', ['status'], unique=False, schema='logger')
    op.create_table('role_claims',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('claim_type', sa.String(length=256), nullable=False),
    sa.Column('claim_name', sa.String(length=256), nullable=False),
    sa.Column('role_id', GUID(), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', GUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_role_claims_role_id'), 'role_claims', ['role_id'], unique=False, schema='identity')
    op.create_table('user_roles',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('user_id', GUID(), nullable=False),
    sa.Column('role_id', GUID(), nullable=False),
    sa.Column('created_by', GUID(), nullable=False),
    sa.Column('created_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_modified_by', GUID(), nullable=False),
    sa.Column('last_modified_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', GUID(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['identity.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_user_roles_role_id'), 'user_roles', ['role_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_user_roles_user_id'), 'user_roles', ['user_id'], unique=False, schema='identity')
    op.create_index('ix_user_roles_role_id_user_id', 'user_roles', ['role_id', 'user_id'], unique=False, schema='identity')
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('affected_columns', sa.JSON(), nullable=True),
    sa.Column('primary_key', sa.JSON(), nullable=True),
    sa.Column('user_id', GUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='logger'
    )
    op.create_index(op.f('ix_logger_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='logger')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logger_audit_logs_user_id'), table_name='audit_logs', schema='logger')
    op.drop_table('audit_logs', schema='logger')
    op.drop_index('ix_user_roles_role_id_user_id', table_name='user_roles', schema='identity')
    op.drop_index(op.f('ix_identity_user_roles_user_id'), table_name='user_roles', schema='identity')
    op.drop_index(op.f('ix_identity_user_roles_role_id'), table_name='user_roles', schema='identity')
    op.drop_table('user_roles', schema='identity')
    op.drop_index(op.f('ix_identity_role_claims_role_id'), table_name='role_claims', schema='identity')
    op.drop_table('role_claims', schema='identity')
    op.drop_index(op.f('ix_logger_email_logs_status'), table_name='email_logs', schema='logger')
    op.drop_table('email_logs', schema='logger')
    op.drop_index(op.f('ix_identity_users_phone_number'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    op.drop_index(op.f('ix_identity_roles_normalized_name'), table_name='roles', schema='identity')
    op.drop_index(op.f('ix_identity_roles_is_system'), table_name='roles', schema='identity')
    op.drop_table('roles', schema='identity')
    # ### end Alembic commands ###
