"""added_users_table

Revision ID: fae0936d74cb
Revises: 
Create Date: 2026-01-02 18:21:32.971653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae0936d74cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='identity'
    )
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_id'), 'users', ['id'], unique=False, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_users_id'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.drop_table('users', schema='identity')
    # ### end Alembic commands ###
